/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as appConversationsIndexRouteImport } from './routes/(app)/conversations/index'
import { Route as appConversationsIdRouteImport } from './routes/(app)/conversations/$id'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appConversationsIndexRoute = appConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => appRouteRoute,
} as any)
const appConversationsIdRoute = appConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof appSettingsRoute
  '/': typeof authIndexRoute
  '/conversations/$id': typeof appConversationsIdRoute
  '/conversations/': typeof appConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof appSettingsRoute
  '/': typeof authIndexRoute
  '/conversations/$id': typeof appConversationsIdRoute
  '/conversations': typeof appConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/': typeof authIndexRoute
  '/(app)/conversations/$id': typeof appConversationsIdRoute
  '/(app)/conversations/': typeof appConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/settings' | '/' | '/conversations/$id' | '/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/' | '/conversations/$id' | '/conversations'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/settings'
    | '/(auth)/'
    | '/(app)/conversations/$id'
    | '/(app)/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authIndexRoute: typeof authIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/conversations/': {
      id: '/(app)/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof appConversationsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/conversations/$id': {
      id: '/(app)/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof appConversationsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appSettingsRoute: typeof appSettingsRoute
  appConversationsIdRoute: typeof appConversationsIdRoute
  appConversationsIndexRoute: typeof appConversationsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appSettingsRoute: appSettingsRoute,
  appConversationsIdRoute: appConversationsIdRoute,
  appConversationsIndexRoute: appConversationsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authIndexRoute: authIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
